//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refresh file state..
        /// </summary>
        internal static string errCannotRefreshFileState {
            get {
                return ResourceManager.GetString("errCannotRefreshFileState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file was not found!.
        /// </summary>
        internal static string errFileNotFound {
            get {
                return ResourceManager.GetString("errFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file path is not valid..
        /// </summary>
        internal static string errFilePathNotValid {
            get {
                return ResourceManager.GetString("errFilePathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while opening the file..
        /// </summary>
        internal static string errIOError {
            get {
                return ResourceManager.GetString("errIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspesified error ocured..
        /// </summary>
        internal static string errUnknownError {
            get {
                return ResourceManager.GetString("errUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuo have unsufficient access rights.
        /// </summary>
        internal static string errUnsuficientRights {
            get {
                return ResourceManager.GetString("errUnsuficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing....
        /// </summary>
        internal static string infoAnalyzing {
            get {
                return ResourceManager.GetString("infoAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estimated.
        /// </summary>
        internal static string infoEstimatedTime {
            get {
                return ResourceManager.GetString("infoEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string infoFinished {
            get {
                return ResourceManager.GetString("infoFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused..
        /// </summary>
        internal static string infoPaused {
            get {
                return ResourceManager.GetString("infoPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausing....
        /// </summary>
        internal static string infoPausing {
            get {
                return ResourceManager.GetString("infoPausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running.
        /// </summary>
        internal static string infoRunningTime {
            get {
                return ResourceManager.GetString("infoRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify text file..
        /// </summary>
        internal static string infoSpecifyTextFile {
            get {
                return ResourceManager.GetString("infoSpecifyTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped on request..
        /// </summary>
        internal static string infoStopped {
            get {
                return ResourceManager.GetString("infoStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string infoStopping {
            get {
                return ResourceManager.GetString("infoStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string titleError {
            get {
                return ResourceManager.GetString("titleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string titleInformation {
            get {
                return ResourceManager.GetString("titleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string titleQuestion {
            get {
                return ResourceManager.GetString("titleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string titleUnhandledException {
            get {
                return ResourceManager.GetString("titleUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string titleWarning {
            get {
                return ResourceManager.GetString("titleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file does not exist!.
        /// </summary>
        internal static string warnFileDoesNotExist {
            get {
                return ResourceManager.GetString("warnFileDoesNotExist", resourceCulture);
            }
        }
    }
}
